package net.darkhax.cserver;

import java.util.Arrays;

import net.darkhax.cserver.util.Reference;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Reference.ID, name = Reference.NAME, version = Reference.VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class CustomServer {

	@SidedProxy(serverSide = Reference.SERVER, clientSide = Reference.CLIENT)
	public static ServerProxy proxy;

	@Mod.Instance(Reference.ID)
	public static CustomServer instance;
	 
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {

		getModMeta(event.getModMetadata());
	}

	private void getModMeta(ModMetadata meta) {

		meta.authorList = Arrays.asList(new String[] { "Darkhax" });
		meta.logoFile = "null";
		meta.autogenerated = false;
		meta.credits = "Provided by Darkhax";
		meta.description = "This mod adds a custom server to the players server list for your modpack / server!";
		meta.url = "www.darkhax.net";
	}
}